"""Deploy contract loader and URDF forward kinematics for fr3-xhand.

The contract JSON is generated by deployment/fr3_xhand/export_contract.py from
a live Isaac Sim env and is the single source of truth for orderings, limits,
frames, and constants. Everything here is numpy, no ROS, no torch.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import yourdfpy
from scipy.spatial.transform import Rotation

import deployment

# Anchor on the editable-installed repo package, this file's own location
# moves into the colcon install space at runtime.
REPO_ROOT = Path(deployment.__file__).resolve().parents[1]
CONTRACT_PATH = REPO_ROOT / "deployment/fr3_xhand/contract/a4h1.json"


def _pose_to_matrix(pos, quat_wxyz) -> np.ndarray:
    t = np.eye(4)
    w, x, y, z = quat_wxyz
    t[:3, :3] = Rotation.from_quat([x, y, z, w]).as_matrix()
    t[:3, 3] = pos
    return t


class Contract:
    def __init__(self, path: Path = CONTRACT_PATH) -> None:
        d = json.loads(Path(path).read_text())
        self.raw = d
        self.joint_order: list[str] = d["joint_order"]
        self.num_arm = int(d["num_arm_joints"])
        self.num_joints = len(self.joint_order)
        self.num_observations = int(d["num_observations"])
        self.num_actions = int(d["num_actions"])
        assert self.num_actions == self.num_joints

        self.joint_lower = np.array(d["joint_lower"])
        self.joint_upper = np.array(d["joint_upper"])
        self.default_joint_pos = np.array(d["default_joint_pos"])

        self.palm_body: str = d["palm_body"]
        self.palm_center_offset = np.array(d["palm_center_offset"])
        self.fingertip_bodies: list[str] = d["fingertip_bodies_lab_order"]
        self.fingertip_offsets = np.array(
            [d["fingertip_offset_by_body"][n] for n in self.fingertip_bodies]
        )

        self.t_world_base = _pose_to_matrix(d["base_pos"], d["base_quat_wxyz"])

        self.control_dt = float(d["control_dt"])
        self.dof_speed_scale = float(d["dof_speed_scale"])
        self.arm_moving_average = float(d["arm_moving_average"])
        self.hand_moving_average = float(d["hand_moving_average"])

        self.obs_list: list[str] = d["obs_list"]
        self.clamp_abs_observations = float(d["clamp_abs_observations"])
        # Keypoint offsets in the object frame are corners scaled by the
        # per-object bbox scale at runtime, see reset_utils.allocate_state_buffers.
        self.keypoint_corners = np.array(d["keypoint_corners"], dtype=np.float64)
        self.keypoint_factor = 0.5 * float(d["object_base_size"]) * float(d["keypoint_scale"])

        self.urdf_path = REPO_ROOT / d["urdf"]
        self.checkpoint_path = REPO_ROOT / d["checkpoint"]
        self.train_yaml_path = Path(path).parent / "a4h1_train.yaml"


class Fk:
    """Forward kinematics in the robot base frame via yourdfpy."""

    def __init__(self, contract: Contract) -> None:
        # FK needs joint frames only, skip mesh loading.
        self.urdf = yourdfpy.URDF.load(
            contract.urdf_path, load_meshes=False, load_collision_meshes=False
        )
        actuated = list(self.urdf.actuated_joint_names)
        assert sorted(actuated) == sorted(contract.joint_order)
        self._perm_urdf_from_canon = np.array(
            [contract.joint_order.index(n) for n in actuated]
        )
        self._links = [contract.palm_body] + contract.fingertip_bodies

    def __call__(self, q_canon: np.ndarray) -> dict[str, np.ndarray]:
        self.urdf.update_cfg(q_canon[self._perm_urdf_from_canon])
        return {n: self.urdf.get_transform(frame_to=n) for n in self._links}
